services:
  app:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_NAME=bmustdb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=1234
      - DATABASE_HOST=192.168.42.86
    networks:
      - express-app

networks:
  express-app: