services:

  mysql:
      image: mysql:latest
      ports:
          - 3307:3306
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
      restart: always
      environment:
          - MYSQL_ROOT_PASSWORD=1234
          - MYSQL_DATABASE=bmustdb
          - TZ=America/Argentina/Mendoza
      networks:
        - express-app
  app:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_NAME=bmustdb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=1234
      - DATABASE_HOST=mysql
    networks:
      - express-app

networks:
  express-app: